### ISSUE TITLE
Print the output from all the kube port-forward underlying commands

### ISSUE THREAD

**Issue by frandieguez** [Tecnobutrul/kubeforward#3]
When running `kubectl port-forward pod/podname 12345` the command prints every connection handled.
```
Forwarding from 127.0.0.1:12345 -> 12345
Forwarding from [::1]:12345 -> 12345
Handling connection for 12345
```

When using the kubeforward I lose that "feature", it would be great to have it back maybe in verbose/debug mode?

**Comment by Tecnobutrul** [comment]
Verbose (-verbose)  and quiet (-quite) modes are now available.
